const {REACT_APP_NETWORK_TIMEOUT, REACT_APP_BASE_API_URL} = process.env;

const DEFAULT_NETWORK_TIMEOUT = 10000;
const AppConfig = Object.freeze({
  BASE_API_URL: REACT_APP_BASE_API_URL,
  NETWORK_TIMEOUT:  REACT_APP_NETWORK_TIMEOUT  ? parseInt(REACT_APP_NETWORK_TIMEOUT, 10): DEFAULT_NETWORK_TIMEOUT,
});

export default AppConfig;